[package]
name = "aram-roulette"
version = "0.1.1"
description = "A deliberately stupid ARAM: Mayhem build randomizer."
license-file = "../LICENSE"
repository = "https://github.com/brunoroq/ARAM-Roulette"
edition = "2021"
rust-version = "1.77.2"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
