/** Generated by scripts/sync-data.mjs from Data Dragon (src/data/verification.json). */
export interface ItemFacts {
  /** shop: buyable on map 12 · auxiliary: consumable/trinket · special: anything else on map 12. */
  readonly kind: 'shop' | 'auxiliary' | 'special';
  /** Recipe components, present for items in a pool item's recipe tree. */
  readonly from?: readonly string[];
  /** Pool item this item automatically transforms from (Data Dragon specialRecipe). */
  readonly transformsFrom?: string;
}

export interface VerificationData {
  readonly champions: Readonly<Record<string, number>>;
  readonly spells: Readonly<Record<string, number>>;
  readonly items: Readonly<Record<string, ItemFacts>>;
}

/** Sanitized result of the native League Client read: the signed-in player's own records only. */
export interface LcuPlayer {
  readonly championId: number;
  readonly spell1Id: number;
  readonly spell2Id: number;
  readonly win: boolean;
  /** item0–item6; item6 is the trinket slot. */
  readonly items: readonly number[];
  readonly augments: readonly number[];
}

export interface LcuGame {
  readonly gameId: number;
  readonly gameCreation: number;
  readonly queueId: number;
  readonly mapId: number | null;
  readonly gameMode: string | null;
  /** Present for Mayhem games only. */
  readonly player: LcuPlayer | null;
}

export type LcuRead =
  | { readonly status: 'ok'; readonly games: readonly LcuGame[] }
  | { readonly status: 'clientNotRunning' | 'notSignedIn' | 'unavailable' | 'desktopOnly' };

/** What the client reports as in progress right now (gameflow session): ID and queue only. */
export type ActiveRead =
  | { readonly status: 'ok'; readonly active: { readonly gameId: number; readonly queueId: number } | null }
  | { readonly status: 'clientNotRunning' | 'unavailable' | 'desktopOnly' };

/** The next eligible Mayhem game didn't match the locked champion or spell pair. Not a loss. */
export type CancelReason = 'CHAMPION_MISMATCH' | 'SPELL_MISMATCH' | 'GAME_ALREADY_COUNTED';
/** The matching game's final inventory can't confirm the build. */
export type UnverifiableReason = 'BUILD_MISMATCH' | 'UNSUPPORTED_ITEM';
export type BuildStatus = 'compatible' | 'mismatch' | 'unsupported';

/** How a run ended. Every resolution names the one game that resolved it. */
export type Resolution =
  | { readonly kind: 'verified'; readonly gameId: number; readonly gameCreation: number; readonly resolvedAt: number }
  | { readonly kind: 'unverifiable'; readonly gameId: number; readonly gameCreation: number; readonly resolvedAt: number; readonly reason: UnverifiableReason }
  | {
    readonly kind: 'cancelled'; readonly gameId: number; readonly gameCreation: number; readonly resolvedAt: number;
    readonly reason: CancelReason; readonly championMatch: boolean; readonly spellsMatch: boolean;
  };

export type RunStatus = 'pending' | Resolution['kind'];

/** One locked challenge in the run queue. Immutable except for its one-time binding and resolution. */
export interface LockedChallenge {
  readonly schema: 2;
  readonly id: string;
  readonly lockedAt: number;
  /** Data Dragon champion ID, for presentation. */
  readonly championId: string;
  /** Riot numeric keys: the verification source of truth. */
  readonly championKey: number;
  readonly spellD: number;
  readonly spellF: number;
  /** Six item IDs in challenge slot order; slot 2 is boots. */
  readonly itemIds: readonly string[];
  /**
   * The exact game this run belongs to: the client reported it in progress right after LOCK IT IN.
   * Absent: the run belongs to the next eligible Mayhem game created after `lockedAt`.
   */
  readonly activeGameId?: number;
  /** Absent while pending. */
  readonly resolution?: Resolution;
}

export interface RunQueue {
  readonly runs: readonly LockedChallenge[];
  /** Games ever bound at LOCK IT IN, kept even if their run is replaced: never bindable again. */
  readonly claimedGameIds: readonly number[];
}

/** Why a pending run is still pending. */
export type PendingReason =
  | 'CLIENT_NOT_RUNNING' | 'NOT_SIGNED_IN' | 'LCU_UNAVAILABLE' | 'DESKTOP_ONLY'
  | 'WAITING_FOR_HISTORY' | 'INCOMPLETE_DATA';

/** One immutable verified challenge run. History cards and stats are built from these alone. */
export interface VerifiedRun {
  readonly challengeId: string;
  readonly lockedAt: number;
  readonly gameId: number;
  /** When the game was created (the client's clock); orders history and streaks. */
  readonly gameCreation: number;
  readonly verifiedAt: number;
  /** Data Dragon champion ID and Riot numeric key. */
  readonly championId: string;
  readonly championKey: number;
  /** Locked spells as [D, F]. */
  readonly lockedSpellIds: readonly [number, number];
  /** Actual spells as reported (spell1Id, spell2Id). */
  readonly actualSpellIds: readonly [number, number];
  /** Six challenge item IDs in slot order. */
  readonly challengeItemIds: readonly string[];
  /** Final item0–item5 as reported (0 = empty). */
  readonly finalItemIds: readonly number[];
  /** Challenge items found completed in the final inventory. Not a purchase order. */
  readonly completedItemIds: readonly string[];
  readonly win: boolean;
}
